# Generated by Django 5.2 on 2025-04-24 13:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onetimepassword',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 24, 13, 21, 12, 93610, tzinfo=datetime.timezone.utc)),
        ),
    ]
