# Generated by Django 5.2 on 2025-04-24 13:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_onetimepassword_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onetimepassword',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 24, 13, 21, 15, 348103, tzinfo=datetime.timezone.utc)),
        ),
    ]
