# Generated by Django 5.2 on 2025-04-24 13:29

import datetime
import django.core.validators
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_onetimepassword_expires_at'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, unique=True, validators=[django.core.validators.RegexValidator(message='Номер телефона должен быть в формате +7XXXXXXXXXX (11 цифр), без знака +', regex='^+7\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='onetimepassword',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 24, 13, 39, 19, 952827, tzinfo=datetime.timezone.utc)),
        ),
    ]
