# Generated by Django 5.2 on 2025-04-24 13:33

import datetime
import django.core.validators
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Введите номер в формате +77xxxxxxxxx', max_length=128, region='KZ', unique=True, validators=[django.core.validators.RegexValidator(message='Номер телефона должен быть в формате +7XXXXXXXXXX (11 цифр), без знака +', regex='^+7\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='onetimepassword',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 24, 13, 43, 41, 640593, tzinfo=datetime.timezone.utc)),
        ),
    ]
