# Generated by Django 5.2 on 2025-04-24 13:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_customuser_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onetimepassword',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 24, 13, 34, 33, 363601, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='onetimepassword',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 24, 13, 44, 33, 363764, tzinfo=datetime.timezone.utc)),
        ),
    ]
