# Generated by Django 5.2 on 2025-04-24 13:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_onetimepassword_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onetimepassword',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 24, 13, 34, 37, 86802, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='onetimepassword',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 24, 13, 44, 37, 87028, tzinfo=datetime.timezone.utc)),
        ),
    ]
