# Generated by Django 5.2 on 2025-04-24 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_onetimepassword_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onetimepassword',
            name='expires_at',
        ),
        migrations.AlterField(
            model_name='onetimepassword',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
