# Generated by Django 5.2 on 2025-04-24 13:37

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_onetimepassword_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Введите номер в формате +77xxxxxxxxx', max_length=128, region='KZ', unique=True),
        ),
    ]
