# Generated by Django 5.2 on 2025-04-24 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.AlterModelTable(
            name='customuser',
            table='users',
        ),
        migrations.AlterModelTable(
            name='onetimepassword',
            table='onetime_passwords',
        ),
    ]
