# Generated by Django 5.2 on 2025-04-24 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_number', models.IntegerField(blank=True, default=1, null=True)),
                ('entrance_number', models.IntegerField(blank=True, default=1, null=True)),
                ('total_floors', models.IntegerField()),
                ('queue', models.IntegerField(blank=True, default=1, null=True)),
                ('deadline_year', models.IntegerField(blank=True, null=True)),
                ('deadline_querter', models.IntegerField(blank=True, null=True)),
                ('total_apartments', models.IntegerField(blank=True, null=True)),
                ('building_status', models.CharField(choices=[('EXСAVATION', 'На стадии котлована'), ('UNDER CONSTRUCTION', 'Строится'), ('COMPLETED', 'Постройка завершена')], default='EXСAVATION', max_length=255)),
                ('link_on_map', models.URLField()),
            ],
            options={
                'db_table': 'blocks',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('APARTMENT', 'Квартира'), ('PARKING', 'Паркинг'), ('BOXROOM', 'Кладовая'), ('COMMERCE', 'Коммерческая недвижимость')], max_length=50)),
            ],
            options={
                'db_table': 'property_categories',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('price_per_sqm', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('rental_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('floor', models.IntegerField()),
                ('area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rooms', models.IntegerField(blank=True, null=True)),
                ('renovation_type', models.CharField(blank=True, max_length=50, null=True)),
                ('wall_material', models.CharField(blank=True, max_length=50, null=True)),
                ('layout', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('entrance', models.IntegerField(blank=True, null=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='properties.block')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='properties.category')),
            ],
            options={
                'db_table': 'properties',
            },
        ),
        migrations.CreateModel(
            name='PropertyPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_link', models.URLField()),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_photos', to='properties.property')),
            ],
            options={
                'db_table': 'property_photos',
            },
        ),
        migrations.CreateModel(
            name='PropertyVideos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_link', models.URLField()),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_videos', to='properties.property')),
            ],
            options={
                'db_table': 'property_videos',
            },
        ),
        migrations.CreateModel(
            name='ResidentialComplex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('class_type', models.CharField(choices=[('STANDARD', 'Стандарт'), ('COMFORT', 'Комфорт'), ('BUSINESS', 'Бизнес'), ('PREMIUM', 'Премиум')], max_length=255)),
                ('construction_technology', models.CharField(max_length=100)),
                ('heating_type', models.CharField(choices=[('GAS', 'Газовое'), ('ELECTRIC', 'Электрическое'), ('CENTRAL', 'Центральное')], max_length=255)),
                ('has_elevator_pass', models.BooleanField(default=False)),
                ('has_elevator_cargo', models.BooleanField(default=False)),
                ('ceiling_height', models.DecimalField(decimal_places=2, max_digits=5)),
                ('block_number', models.IntegerField()),
                ('down_payment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('installment_plan', models.CharField(max_length=50)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('link_on_map', models.URLField()),
                ('description_full', models.TextField()),
                ('description_short', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='residential_complexes', to='location.district')),
            ],
            options={
                'db_table': 'residential_complexes',
            },
        ),
        migrations.AddField(
            model_name='block',
            name='complex',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='properties.residentialcomplex'),
        ),
    ]
