# Generated by Django 5.2 on 2025-04-30 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('APARTMENT', 'Apartment'), ('PARKING', 'Parking'), ('BOXROOM', 'Boxroom'), ('COMMERCE', 'Commerce')], max_length=50),
        ),
        migrations.CreateModel(
            name='ResidentialComplexPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_link', models.URLField()),
                ('complex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='residential_complex_photos', to='properties.residentialcomplex')),
            ],
            options={
                'db_table': 'residential_complex_photos',
            },
        ),
    ]
