# Generated by Django 5.2 on 2025-04-30 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_alter_category_name_residentialcomplexphotos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='category',
            field=models.CharField(choices=[('APARTMENT', 'Apartment'), ('PARKING', 'Parking'), ('BOXROOM', 'Boxroom'), ('COMMERCE', 'Commerce')], max_length=50),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
