# Generated by Django 5.2 on 2025-05-01 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_alter_property_category_delete_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residentialcomplex',
            name='construction_technology',
            field=models.CharField(choices=[('MONOLITHIC', 'Monolithic'), ('PRECAST LARGE-PANEL', 'Precast large-panel'), ('MASONRY', 'Masonry')], max_length=100),
        ),
        migrations.AlterField(
            model_name='residentialcomplex',
            name='description_full',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='residentialcomplex',
            name='description_short',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='residentialcomplex',
            name='down_payment',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='residentialcomplex',
            name='installment_plan',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='residentialcomplex',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='residentialcomplex',
            name='link_on_map',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='residentialcomplex',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=10, null=True),
        ),
    ]
