# Generated by Django 5.2 on 2025-05-01 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_alter_residentialcomplex_construction_technology_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='building_status',
            field=models.CharField(choices=[('EXСAVATION', 'At the excavation stage'), ('UNDER CONSTRUCTION', 'Under construction'), ('COMPLETED', 'The construction is completed')], default='EXСAVATION', max_length=255),
        ),
        migrations.AlterField(
            model_name='residentialcomplex',
            name='class_type',
            field=models.CharField(choices=[('STANDARD', 'Standard'), ('COMFORT', 'Comfort'), ('BUSINESS', 'Business'), ('PREMIUM', 'Premium')], max_length=255),
        ),
        migrations.AlterField(
            model_name='residentialcomplex',
            name='heating_type',
            field=models.CharField(choices=[('GAS', 'Gas heating'), ('ELECTRIC', 'Electric heating'), ('CENTRAL', 'Central heating')], max_length=255),
        ),
    ]
