# Generated by Django 5.2 on 2025-05-04 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_alter_block_building_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='description',
        ),
        migrations.RemoveField(
            model_name='property',
            name='entrance',
        ),
        migrations.RemoveField(
            model_name='property',
            name='renovation_type',
        ),
        migrations.RemoveField(
            model_name='property',
            name='wall_material',
        ),
    ]
