# Generated by Django 5.2 on 2025-04-24 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'В ожидании'), ('RESERVED', 'Забронировано'), ('PAID', 'Оплачено'), ('CANCELED', 'Отменено'), ('COMPLETED', 'Завершено')], default='PENDING', max_length=50)),
                ('purchase_purpose', models.CharField(choices=[('BUYING', 'Покупка'), ('RENTING', 'Аренда')], default='BUYING', max_length=50)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_purchases', to='properties.property')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'property_purchases',
            },
        ),
    ]
