# Generated by Django 5.2 on 2025-05-01 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertypurchase',
            name='purchase_purpose',
            field=models.CharField(choices=[('BUYING', 'Buying'), ('RENTING', 'Renting')], default='BUYING', max_length=50),
        ),
        migrations.AlterField(
            model_name='propertypurchase',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('RESERVED', 'Reserved'), ('PAID', 'Paid'), ('CANCELED', 'Canceled'), ('COMPLETED', 'Completed')], default='PENDING', max_length=50),
        ),
    ]
